### ISSUE TITLE
"co" option toggle as a configurable option

### ISSUE THREAD

**Issue by pedrosans** [tpope/vim-unimpaired#150]
Hi, to toggle vim's configurations with the "co" keys is more comfortable to type than the '=o', can it be broth back as a configurable option?

**Comment by tpope** [comment]
The big problem with `co` is that Netrw breaks it with a dumb `<nowait>` map.  I agree that `=o` is a bit too uncomfortable. What do you think about using `yo`?

**Comment by pedrosans** [comment]
`yo` would be more comfortable to type, but I can't think of a mnemonic for the `y`

**Comment by tpope** [comment]
Long past caring about that.

**Comment by ri-aje** [comment]
hi, can we make this =/y letter configurable? I actually prefer the = key much better than y which conflicts with my paste hotkey. this is because I don't use the default qwerty keyboard layout and that in itself is already a challenge due to vim's design based on the standard layout, and picking y here just made things worse.

**Comment by tpope** [comment]
The new map customization system is tailor made for this. What key do you use for yank?

**Comment by ri-aje** [comment]
I try to stick to the default. from a hardware perspective, I still use the physical y key for copy and p key for paste to serve my muscle memory. these keys don't generate the actual keycode for y and p though, instead they generate j and y under my layout mapping (in case you are interested, it's colemak layout with some slight adaption), which apparently messes up vim's key design. to revert this effect, I inject custom vim mapping so my fingers may continue function with vim's key design. my y key (which is the physical p key) ends up functioning as paste, but that is only after vim's mapping translation. with this change, however, there are multiple y* hotkeys so vim starts to wait a bit for every y press to determine whether I am pressing y or y* something, and that makes all paste operations pause a little, which is annoying.

what is the "new map customization system" you are talking? is it a new thing in vim-unimpaired or vim8? thanks.

**Comment by tpope** [comment]
It's new to unimpaired and someo of my other plugins. Try
```viml
let g:nremap = {"y": "j"}
let g:xremap = {"y": "j"}
let g:oremap = {"y": "j"}
```

The idea here is that *all* plugins (or at least the ones I have any say in) with `y` maps will change to `j` maps.

The more I think about it, the more I think having multiple dictionaries is redundant.

**Comment by ri-aje** [comment]
it works. thanks. given these configs, curious to know why then #150 requires code change at all? seems like one could just inject {"=": "y"} to reach the same effect.

**Comment by tpope** [comment]
Because then **you** wouldn't be able to do `let g:nremap = {"y": "j"}` since the original map would still be `=`.

**Comment by ri-aje** [comment]
I am saying with the original code before your change in [c4f32e](https://github.com/tpope/vim-unimpaired/commit/c4f32e9d86178de85e91cd1600f757803b897744), I could just put `let g:nremap = {"=": "y"}` in vimrc to have `yo` functions as `=o` which seems to be what was asked in this issue. since the problem can be solved with a config change, why do it with code change. make sense?

**Comment by tpope** [comment]
I've gotten enough pushback to know that some nontrivial percentage of users will be remapping (even I'm tempted), and I don't want fragmentation.  Anyone can shove `nmap <Leader>abc :set invlist!<CR>` in their vimrc. A significant design goal of unimpaired is standardizing what the mappings should be.

**Comment by tpope** [comment]
I have brought back `co` with a soft deprecation warning. It's clearly too contentious to take away before 2.0.

**Comment by sodapopcan** [comment]
Oh heh 🤪 Thank you much for letting me know.  I hadn't actually updated in several days so I didn't have the `yo` commit but noticed `co` wasn't working then found this issue and updated in haste.

Side note: big a fan of `]op` and `[op` over the old way in spite of the extra keystroke.

**Comment by kiryph** [comment]
### Update for Netrw v162 or newer

Netrw v162 has changed `netrw-c` to `netrw-cd` and has introduced the new mappings `netrw-cb` and `netrw-cB`.

**IMPORTANT** If you want to check this for yourself, please download the new netrw version from http://www.drchip.org/astronaut/vim/index.html#NETRW. Upstream vim contains currently (24.09.2018) a version inconsistency between documentation and the actual file `autoload/netrw.vim` which defines the mappings: the documentation currently claims v162 but the `autoload/netrw.vim` is still v156.

**Comment by Asheq** [comment]
For what it's worth, I prefer the prefixes
`yr`
`[r`
`]r`

over

`yo`
`[o`
`]o`

since `y`, `[`, and `]` are on the opposite hand from `r`.

The mnemonic would be `you rotate` a setting's value or something.

I've been feeling hints of RSI recently so I've been hyper-aware of key-combos that hurt or feel uncomfortable. I especially feel the `yo` for some reason. Otherwise I wouldn't really care.

Another option would be to make the prefixes configurable:
```
let g:unimpaired_on_prefix = '[r'
let g:unimpaired_off_prefix = ']r'
let g:unimpaired_toggle_prefix = 'yr'
```

**Comment by mnacamura** [comment]
`map co yo` still keeps `yo`  left and I feel it a bit annoying.

How about replacing hard coded `yo` with something like `[unimpaired_yo]` and adding
```vim
nmap yo [unimpaired_yo]
nnoremap [unimpaired_yo] <Nop>
```
so that anyone who wants to remap `yo` can do
```vim
nunmap yo
nmap whatever [unimpaired_yo]
```

**Comment by tpope** [comment]
I have added `<Plug>(unimpaired-enable)`, `<Plug>(unimpaired-disable)`, and `<Plug>(unimpaired-toggle)`.
