### ISSUE TITLE
Doesn't play nice with repmo.vim

### ISSUE THREAD

**Issue by HaleTom** [tpope/vim-unimpaired#184]
`vim-unimpaired` doesn't play nicely with [`repmo` - repeat motions for which a count was given](https://github.com/vim-scripts/repmo.vim)

The configuration which I expect to work is:

```viml
" GitGutter
:nmap <expr> ]c repmo#Key('<Plug>GitGutterNextHunk', '<Plug>GitGutterPrevHunk')
:nmap <expr> [c repmo#Key('<Plug>GitGutterPrevHunk', '<Plug>GitGutterNextHunk')

" Unimpaired - See after/plugin/repmo-unimpaired.vim
nmap <expr> ]q repmo#Key('<plug>unimpairedQNext', '<plug>unimpairedQPrevious')
nmap <expr> [q repmo#Key('<plug>unimpairedQPrevious', '<plug>unimpairedQNext')
nmap <expr> ]l repmo#Key('<Plug>unimpairedLNext', '<plug>unimpairedLPrevious')
nmap <expr> [l repmo#Key('<plug>unimpairedLPrevious', '<plug>unimpairedLNext')
nmap <expr> ]n repmo#Key('<plug>unimpairedContextNext', '<plug>unimpairedContextPrevious')
nmap <expr> [n repmo#Key('<plug>unimpairedContextPrevious', '<plug>unimpairedContextNext')
omap <expr> ]n repmo#Key('<plug>unimpairedContextNext', '<plug>unimpairedContextPrevious')
omap <expr> [n repmo#Key('<plug>unimpairedContextPrevious', '<plug>unimpairedContextNext')
```

The `gitgutter` config works fine, but the only way that I can get the `unimpaired` config to work is to [put those line in `~/.vim/after/plugin/repmo-unimpaired.vim`](https://github.com/Houl/repmo-vim/issues/3#issuecomment-500773521).

I'd prefer to avoid the `after/` hack.  What causes this plugin to not work with `repmo` the way that `gitgutter` does?

**Comment by kiryph** [comment]
I had a look at following line `if`:
https://github.com/tpope/vim-unimpaired/blob/e77923053fbce11323194ed04113b8d966be959c/plugin/unimpaired.vim#L35-L37

`!~?` means regexp doesn't match with ignore case
`!=#` means not equal with match case

`flags !~? '<unique>'` is true when `[l` etc are mapped with 

https://github.com/tpope/vim-unimpaired/blob/e77923053fbce11323194ed04113b8d966be959c/plugin/unimpaired.vim#L68-L72

This means `empty(maparg(head.tail, mode))` can be true or false and therefore vim-unimpaired overwrites regardless whether `[l` are already defined.

If `<unique>` is intended to overwrite regardless whether a maparg exists and if it is not given check if there is already a mapping, I would rewrite the `if` condition as following

```diff
diff --git a/plugin/unimpaired.vim b/plugin/unimpaired.vim
index c9e7a75..76d02c7 100644
--- a/plugin/unimpaired.vim
+++ b/plugin/unimpaired.vim
@@ -32,7 +32,7 @@ function! s:maps() abort
       let tail = matchstr(head, '<[^<>]*>$\|.$') . tail
       let head = substitute(head, '<[^<>]*>$\|.$', '', '')
     endwhile
-    if head !=# '<skip>' && (flags !~? '<unique>' || empty(maparg(head.tail, mode)))
+    if head !=# '<skip>' && (flags =~? '<unique>' || empty(maparg(head.tail, mode)))
       exe mode.'map' flags head.tail rhs
     endif
   endfor
```
However, I am not completely sure if this is the intention.

**Comment by HaleTom** [comment]
Thanks @kiryph!

@tpope Would you accept a PR of the above?

**Comment by tpope** [comment]
The current behavior matches my intention: override the map *unless* `<unique>` is specified. This matches how Vim's native `<unique>` works, minus spamming the user with a dumb error message.

It's an inconvenience to define your override in `after/` but it's by no means a hack. Generally speaking I am a fan of mild inconvenience because it discourages mindless cargo culting (although it's certainly debatable whether it's justified here).

A good middle ground might be to check if `maparg(head.tail, mode)` contains `rhs`. That is, if `]q` map includes `<Plug>unimpairedQNext`, then the user almost certainly knows what they're doing and we should not override their map.

**Comment by kiryph** [comment]
> A good middle ground might be to check if maparg(head.tail, mode) contains rhs. That is, if ]q map includes <Plug>unimpairedQNext, then the user almost certainly knows what they're doing and we should not override their map.

Does this mean the `if` should become
```diff
diff --git a/plugin/unimpaired.vim b/plugin/unimpaired.vim
index c9e7a75..72ccde9 100644
--- a/plugin/unimpaired.vim
+++ b/plugin/unimpaired.vim
@@ -32,7 +32,8 @@ function! s:maps() abort
       let tail = matchstr(head, '<[^<>]*>$\|.$') . tail
       let head = substitute(head, '<[^<>]*>$\|.$', '', '')
     endwhile
-    if head !=# '<skip>' && (flags !~? '<unique>' || empty(maparg(head.tail, mode)))
+    if head !=# '<skip>' && match(maparg(head.tail, mode), rhs) == -1 &&
+          \ (flags !~? '<unique>' || empty(maparg(head.tail, mode)))
       exe mode.'map' flags head.tail rhs
     endif
   endfor
```

**Notes** (ignore if you wish)

I think users should be completely free to assign their own key bindings (even though I am very happy with the default ones from vim-unimpaired). This means I would allow user to assign something completely different to `<Plug>unimpairedQNext` and use `]q` also for something else.
Also allowing to use `<plug>` mappings provides flexibility (repmo-vim). I have user with a foreign keyboard layout, the dvorak layout (or other "superior" layout) or even a custom keyboard layout in mind as well.

For ftplugins there are two official recommendations in `:h write-filetype-plugin` regarding mappings:

```
An example of how to define functionality in a filetype plugin: >

	if !hasmapto('<Plug>JavaImport')
	  map <buffer> <unique> <LocalLeader>i <Plug>JavaImport
	endif
	noremap <buffer> <unique> <Plug>JavaImport oimport ""<Left><Esc>

|hasmapto()| is used to check if the user has already defined a map to
<Plug>JavaImport.  If not, then the filetype plugin defines the default
mapping.
"<unique>" is used to give an error message if the mapping already exists or
overlaps with an existing mapping.
```
Secondly
```
The user must have a chance to disable the mappings in a filetype plugin,
without disabling everything.  Here is an example of how this is done for a
plugin for the mail filetype: >

	" Add mappings, unless the user didn't want this.
	if !exists("no_plugin_maps") && !exists("no_mail_maps")
	  " Quote text by inserting "> "
	  if !hasmapto('<Plug>MailQuote')
	    vmap <buffer> <LocalLeader>q <Plug>MailQuote
	    nmap <buffer> <LocalLeader>q <Plug>MailQuote
	  endif
	  vnoremap <buffer> <Plug>MailQuote :s/^/> /<CR>
	  nnoremap <buffer> <Plug>MailQuote :.,$s/^/> /<CR>
	endif

Two global variables are used:
|no_plugin_maps|	disables mappings for all filetype plugins
|no_mail_maps|		disables mappings for the "mail" filetype
```

I think the second point is not really relevant for vim-unimpaired. vim-unimpaired is mainly a plugin providing a consistent set of mappings. Disabling all mappings does not leave much functionality behind. But this could still be useful if someone wants only a small subset of mappings from vim-unimpaired and only defines those desired manually. However, this means the official example is not perfect since the `<plug>` mappings should be outside of the `if !exists("no_plugin_maps") ...`.

**Comment by tpope** [comment]
You'll want to use `stridx()` for a literal comparison, and I *think* it'll be a third `||` clause in the inner parentheses.

> I think users should be completely free to assign their own key bindings (even though I am very happy with the default ones from vim-unimpaired).

I agree, it's only a question of how.

> This means I would allow user to assign something completely different to `<Plug>unimpairedQNext` and use `]q` also for something else.
> Also allowing to use `<plug>` mappings provides flexibility (repmo-vim). I have user with a foreign keyboard layout, the dvorak layout (or other "superior" layout) or even a custom keyboard layout in mind as well.

I have a solution for Dvorak/foreign keyboard problem, but not having the problem myself it's hard for me to gauge if it's a good one. https://github.com/tpope/vim-unimpaired/commit/1a4bfc16b6254a8586f76eb976b9c57b7014c5e7

> For ftplugins there are two official recommendations in `:h write-filetype-plugin` regarding mappings:
> 
> ```
> An example of how to define functionality in a filetype plugin: >
> 
> 	if !hasmapto('<Plug>JavaImport')
> 	  map <buffer> <unique> <LocalLeader>i <Plug>JavaImport
> 	endif
> 	noremap <buffer> <unique> <Plug>JavaImport oimport ""<Left><Esc>
> 
> |hasmapto()| is used to check if the user has already defined a map to
> <Plug>JavaImport.  If not, then the filetype plugin defines the default
> mapping.
> "<unique>" is used to give an error message if the mapping already exists or
> overlaps with an existing mapping.
> ```

I am familiar with this passage and utterly despise it. If I find myself deleting paragraphs a lot, and do `nmap <Space> dap`, Vim doesn't say "oh, you have a map to delete a paragraph, I guess I'll disable the built-in". So why then, should a plugin disable it's built-in map just because the user provided their own? It's not hurting anything, disabling the map just confuses things and makes it harder for someone else to use your computer.

And `<unique>` is garbage. You're just creating busy work for the user to get rid of an error message. Either override the other map or defer to it, don't fucking bitch to the user about it. They might not even use the map at all.

My system in unimpaired it to override by default, and repurpose `<unique>` to mean "defer to the original map". But if you wanna rip out `<unique>` entirely and always defer to the original map, sure, I'll merge and we can find out firsthand if there are unintended consequences.

> ```
> The user must have a chance to disable the mappings in a filetype plugin,
> without disabling everything.  Here is an example of how this is done for a
> plugin for the mail filetype: >
> 
> 	" Add mappings, unless the user didn't want this.
> 	if !exists("no_plugin_maps") && !exists("no_mail_maps")
> 	  " Quote text by inserting "> "
> 	  if !hasmapto('<Plug>MailQuote')
> 	    vmap <buffer> <LocalLeader>q <Plug>MailQuote
> 	    nmap <buffer> <LocalLeader>q <Plug>MailQuote
> 	  endif
> 	  vnoremap <buffer> <Plug>MailQuote :s/^/> /<CR>
> 	  nnoremap <buffer> <Plug>MailQuote :.,$s/^/> /<CR>
> 	endif
> 
> Two global variables are used:
> |no_plugin_maps|	disables mappings for all filetype plugins
> |no_mail_maps|		disables mappings for the "mail" filetype
> ```
> 
> I think the second point is not really relevant for vim-unimpaired. vim-unimpaired is mainly a plugin providing a consistent set of mappings. Disabling all mappings does not leave much functionality behind. But this could still be useful if someone wants only a small subset of mappings from vim-unimpaired and only defines those desired manually. However, this means the official example is not perfect since the `<plug>` mappings should be outside of the `if !exists("no_plugin_maps") ...`.

Horrible example aside, I agree, and would add my usual convention of `g:unimpaired_no_maps` if someone really wanted it.

**Comment by kiryph** [comment]
> You'll want to use `stridx()` for a literal comparison,

Thanks for the suggestion:
```diff
diff --git a/plugin/unimpaired.vim b/plugin/unimpaired.vim
index c9e7a75..adca926 100644
--- a/plugin/unimpaired.vim
+++ b/plugin/unimpaired.vim
@@ -32,7 +32,8 @@ function! s:maps() abort
       let tail = matchstr(head, '<[^<>]*>$\|.$') . tail
       let head = substitute(head, '<[^<>]*>$\|.$', '', '')
     endwhile
-    if head !=# '<skip>' && (flags !~? '<unique>' || empty(maparg(head.tail, mode)))
+    if head !=# '<skip>' && stridx(maparg(head.tail, mode), rhs) == -1 &&
+          \ (flags !~? '<unique>' || empty(maparg(head.tail, mode)))
       exe mode.'map' flags head.tail rhs
     endif
   endfor
```

> and I *think* it'll be a third `||` clause in the inner parentheses.

In my understanding this is not what the OP wants.

vim-unimpaired would still overwrite his mappings from vimrc since `flags !~? '<unique>'` is true for `]q` etc which means the new third `||` clause does not matter either. I tried
```diff
diff --git a/plugin/unimpaired.vim b/plugin/unimpaired.vim
index c9e7a75..3198be8 100644
--- a/plugin/unimpaired.vim
+++ b/plugin/unimpaired.vim
@@ -32,7 +32,8 @@ function! s:maps() abort
       let tail = matchstr(head, '<[^<>]*>$\|.$') . tail
       let head = substitute(head, '<[^<>]*>$\|.$', '', '')
     endwhile
-    if head !=# '<skip>' && (flags !~? '<unique>' || empty(maparg(head.tail, mode)))
+    if head !=# '<skip>' && (stridx(maparg(head.tail, mode), rhs) == -1 ||
+          \ flags !~? '<unique>' || empty(maparg(head.tail, mode)))
       exe mode.'map' flags head.tail rhs
     endif
   endfor
```
I confirm that this diff does not resolve this issue. OP would still have to place the mappings in `after`.

> I am familiar with this passage and utterly despise it. If I find myself deleting paragraphs a lot, and do `nmap <Space> dap`, Vim doesn't say "oh, you have a map to delete a paragraph, I guess I'll disable the built-in". So why then, should a plugin disable it's built-in map just because the user provided their own? It's not hurting anything, disabling the map just confuses things and makes it harder for someone else to use your computer.

I agree. vim help is not carved in stone though. One could raise an issue on vimdev about improving this section in vim help. However, I feel like this should do someone who has a high enough reputation when it comes to plugin writing.

> And `<unique>` is garbage. You're just creating busy work for the user to get rid of an error message. Either override the other map or defer to it, don't fucking bitch to the user about it. They might not even use the map at all.

Do you mean `<unique>` in general or as used in this example?

> My system in unimpaired is to override by default, and repurpose `<unique>` to mean "defer to the original map" (which is what Vim does after gratuitously complaining to the user about it). But if you wanna rip out `<unique>` entirely and always defer to the original map, sure, I'll merge and we can find out firsthand if there are unintended consequences.

This has not been totally clear to me yet.

I was trying to help to understand why vim-unimpaired was overwriting the user mappings and have no intentions to rip out anything from vim-unimpaired. It looks like that the usage of `<unique>` in vim-unimpaired has related issues I am not familiar with.

I was hoping that the middle ground route resolves this issue.

**Comment by tpope** [comment]
> > and I _think_ it'll be a third `||` clause in the inner parentheses.
> 
> In my understanding this is not what the OP wants.
> 
> vim-unimpaired would still overwrite his mappings from vimrc since `flags !~? '<unique>'` is true for `]q` etc which means the new third `||` clause does not matter either.

You're right. Your patch is probably fine, but at this point I am in favor of ripping out `<unique>` entirely and just always refusing to override an existing map.

> > I am familiar with this passage and utterly despise it. If I find myself deleting paragraphs a lot, and do `nmap <Space> dap`, Vim doesn't say "oh, you have a map to delete a paragraph, I guess I'll disable the built-in". So why then, should a plugin disable it's built-in map just because the user provided their own? It's not hurting anything, disabling the map just confuses things and makes it harder for someone else to use your computer.
> 
> I agree. vim help is not carved in stone though. One could raise an issue on vimdev about improving this section in vim help. However, I feel like this should do someone who has a high enough reputation when it comes to plugin writing.

Unfortunately I don't have time for these sorts of things.

> > And `<unique>` is garbage. You're just creating busy work for the user to get rid of an error message. Either override the other map or defer to it, don't fucking bitch to the user about it. They might not even use the map at all.
> 
> Do you mean `<unique>` in general or as used in this example?

I think producing an error on startup is a horrible end user experience and should be avoided at all costs. The cost here is pretty low: a user might call a map from plugin A (or their vimrc) and instead calls a map from plugin B. A pro can troubleshoot this easily. It might trip up a novice for a bit, but that same novice is going to have no idea what to do with E227 either, so all you're doing is turning possible confusion into guaranteed confusion.

**Comment by HaleTom** [comment]
Thanks a bunch for fixing this!
