### ISSUE TITLE
In the most recent changes, 'e' (`[oe`, `]oe`, `yoe`) was added to manage `spell` -- why change away from 's'?

### ISSUE THREAD

**Issue by nebbish** [tpope/vim-unimpaired#225]
I have a local edit that I have not yet setup as a pull request that adds two letters to the option toggle mechanism:   'm' for `bomb` and 'e' for `expandtab`.

Those have been very handy to me because my co-workers argue over tabs, and some of them completely mis-handle unicode BOM marks.

Is there something on your mind about 'e' for `spell` that has not fully blossomed yet?   I can adjust my local edit and then my muscle memory ;)

If not...    can you setup 'e' to manage `expandtab` instead?
And maybe throw in 'm' for `bomb` too :D

**Comment by tpope** [comment]
I'm seriously considering moving the option maps to [`<s`, `>s`, and `=s`](https://github.com/tpope/vim-unimpaired/blob/e4006d68cd4f390efef935bc09be0ce3bd022e72/doc/unimpaired.txt#L96-L97), and the double `ss` for `:set spell` just didn't sit right.

You can voice your support for `expandtab` over on #140. I'm a little hesitant to go there because then every other indenting option is on the table.

As for `'bomb'`, I can save you some false hope and say that I don't see that happening. In all my years maintaining Vim plugins, I don't think I've heard from a single other user of that option. And I don't think I've seen a BOM in the wild. Maybe on Windows.
