### ISSUE TITLE
Add mapping for next and preview

### ISSUE THREAD

**Issue by andreicristianpetcu** [tpope/vim-unimpaired#60]
I want to go to the next item in quickfix list and preview it. I want to map something like "]g" to "]c" + "go" and "[g" to "[c" + "go".
I think this can be a very useful feature. If you like it I can try to implement it and add a pull request. I never wrote any vimscript before.

**Comment by Comux** [comment]
'''
搭配前文介绍过的 vim-unimpaired 插件，你还可以在不操作 quickfix窗口的情况下，使用快捷键进行上下结果跳转，
'''
https://zhuanlan.zhihu.com/p/36279445
I also want to know how to get this implemented!

**Comment by tpope** [comment]
This seems easy enough to rig up.

1. Write a function that saves the current window id, calls `exe "normal \<CR>"` to select the file under the cursor, and then returns to that window id.
2. Map `J` and `K` (or whatever) to `j` and `k` followed by calling that function.

Since this would be specific to quickfix buffers (perhaps defined in `after/ftplugin/quickfix.vim`), I don't think Unimpaired is a good place to live. Although if someone gets it working, do share, perhaps I'll change my mind.
