### ISSUE TITLE
Would like to see "ya" and "yi" enabled.

### ISSUE THREAD

**Issue by introom** [tpope/vim-unimpaired#90]
Just like "yo" and "yO", having "ya" and "yi" is really convenient.

The problem with "yo" and "yO" is, sometimes you don't need an extra new line.

**Comment by tpope** [comment]
`ya` and `yi` are valid beginnings for commands like `yap` and `yiw`. See also #67.

**Comment by jlmuir** [comment]
Tim, thanks for writing this excellent plugin!

I too have wished for `ya` and `yi`.  I use `yo` and `yO` a lot and love them!  However, I also have many times when I don't want to paste on a new line; I just want to insert at the current cursor position.  For example, say I want to replace `https://example.org` with the contents of my OS clipboard (which contains a new URL) in a file like this:

```XML
<?xml version="1.0"?>
<what>
  <ever>
    <url>https://example.org</url>
  </ever>
</what>
```

How would you typically do that?

Without `yi`, and assuming the cursor is positioned at the beginning of the file, I would do the following (where `<Cmd-V>` triggers my OS' paste command):

```
/ht<CR>
dt<
:set paste<CR>
i
<Cmd-V>
<Esc>
:set nopaste<CR>
```

That feels pretty awkward.  I know I can use the `"+` register (or `"*` for the X11 primary) to paste from the OS clipboard (if Vim has been compiled with this support) without needing to put Vim in Paste mode, but that doesn't work for a remote Vim where I have the text to paste in my OS clipboard, I'm connected to a machine via SSH in a terminal, I'm editing the file with Vim, and I want to paste into that file.

Thanks!

**Comment by tpope** [comment]
To answer your literal question, I wouldn't bother with paste mode for a single line URL: `cit<Cmd-V><Esc>`, done. Change it to a multi-line example and it does get more awkward, but a big part of that is adding the initial newline, reindenting afterwards, etc. I'm reticent to add more maps just to save a couple of keystrokes while still leaving things fundamentally awkward.

**Comment by jlmuir** [comment]
Fair enough.  Thanks for answering my literal question.

For me, *not* using Paste mode has become harder for two reasons:

1. Since I have a MacBook Pro which does not have an actual Escape key but rather a virtual one in the touch bar, I remapped `<Esc>` to `jj`.  (Maybe that was a mistake and hitting the virtual Escape key would not have been that hard?  I decided to switch when I got the MBP with the touch bar, so that's where I am right now.)  Then I ran into trouble pasting a URL that contained two consecutive `j` characters (e.g., `https://example.org/jUw7rvHqIjjzrYmF0pyz9Q`).  I had this happen at least once, which drove me to be more fastidious about using Paste mode.  (I've heard some people remap to `jk`, but that could have the same problem.)  If I abandon using Paste mode in this situation, I would wish to not need to visually scan each URL I copy for an occurrence of `jj` before pasting.  Maybe I shouldn't worry about it, though, and if the paste causes sad edits, motions, etc., I could just undo them?

2. I read this [bracketed paste mode](https://cirw.in/blog/bracketed-paste) blog post which references a [proof of concept](http://thejh.net/misc/website-terminal-copy-paste) showing a danger of copying text from a web page and pasting it into a terminal.  By extension, I considered this a danger for pasting into Vim.  (Perhaps that's just silly; the chances of running into such an attack are really slim....)  Now that I've just dug up that blog post, I see that it references the [vim-bracketed-paste](https://github.com/ConradIrwin/vim-bracketed-paste) plugin by the blog post author which interestingly claims to handle bracketed-paste-mode in Vim for an automatic Paste mode.  Maybe that's just what I'm looking for; I've never tried it, though.

**Comment by tpope** [comment]
1. I've used a lot of people's Vim configs over the years so I speak from experience when I say that `jj` style maps are one of the worst perversions you can inflict on yourself. Do yourself a massive favor and switch to `CTRL-[` or `CTRL-C`.
2. The biggest threat here is that someone will embed a literal escape character to break out of insert mode, and paste mode won't save you from that. If they can't embed control characters, you should be fine, unless you give them a `jj` backdoor enabling `jj:!rm -rf /`. Another nail in the `jj` coffin.

**Comment by jlmuir** [comment]
OK, I've switched to `CTRL-[`.  Thanks for the suggestion!
